'use client';
import { useState, type ChangeEvent, type DragEvent } from 'react';
import Link from 'next/link';
import { Check, FileText, Link2, UploadCloud, Sparkles } from 'lucide-react';

export default function Analyze(){
 const [tab,setTab]=useState<'upload'|'manual'|'public'>('upload');
 const [file,setFile]=useState<File|null>(null); const [drag,setDrag]=useState(false); const [running,setRunning]=useState(false); const [done,setDone]=useState(false);
 const setSelected=(f:File|null)=>{setFile(f);setDone(false)};
 const onDrop=(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDrag(false);setSelected(e.dataTransfer.files?.[0]??null)};
 const onChange=(e:ChangeEvent<HTMLInputElement>)=>setSelected(e.target.files?.[0]??null);
 const start=()=>{setRunning(true);setTimeout(()=>{setRunning(false);setDone(true)},1400)};
 return <main className="content"><div className="section-head"><div><h1 className="page-title">Analyze a project</h1><p className="page-subtitle">Bring in a documented innovation attempt, manually describe it, or select from a curated public-source catalog.</p></div><span className="status green">Demo Analysis</span></div><div className="card"><div className="tabs">{[['upload','Upload Project'],['manual','Manual Entry'],['public','Public Sources']].map(([id,label])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>setTab(id as any)}>{label}</button>)}</div><div className="card-pad">{tab==='upload' && <><div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={onDrop} className={`dropzone ${drag?'active':''}`}><div><div className="drop-icon"><UploadCloud size={20}/></div><div style={{fontSize:13,fontWeight:700}}>{file ? file.name : 'Drop a project document here'}</div><div style={{color:'#68727d',fontSize:10,marginTop:6}}>PDF · DOCX · PPTX · TXT · MD</div><label className="btn mt-3" style={{display:'inline-flex'}}>Choose file<input type="file" accept=".pdf,.docx,.pptx,.txt,.md" onChange={onChange} style={{display:'none'}}/></label></div></div><div className="grid grid-2 mt-4"><div className="quick-link"><div style={{display:'flex',gap:10,alignItems:'center'}}><FileText size={14} color="#7d8792"/><div><strong>{file?.name ?? 'No file selected'}</strong><div style={{color:'#6e7883',fontSize:10,marginTop:3}}>{file ? `${Math.round(file.size/1024)} KB · selected` : 'Ready for upload'}</div></div></div><span>source</span></div><div className="quick-link"><div style={{display:'flex',gap:10,alignItems:'center'}}><Link2 size={14} color="#7d8792"/><div><strong>Evidence grounding</strong><div style={{color:'#6e7883',fontSize:10,marginTop:3}}>Claims will be linked to extracted evidence</div></div></div><span className="green">ON</span></div></div><div className="mt-4" style={{display:'flex',justifyContent:'flex-end'}}><button className="btn primary" onClick={start} disabled={!file || running}>{running ? 'Processing…':'Analyze Project'}<Sparkles size={14}/></button></div></>}{tab==='manual' && <Manual start={start} running={running}/>} {tab==='public' && <Public/>}{done && <div className="callout mt-4"><strong>Analysis created.</strong> Demo output is ready. <Link href="/projects/p1/dna" className="link">Open Innovation DNA →</Link></div>}</div></div></main>
}
function Manual({start,running}:{start:()=>void,running:boolean}){return <><div className="form-grid"><Field label="Project Name"/><Field label="Industry"/><Field label="Problem Addressed" full area/><Field label="Objective" full area/><Field label="Technologies Used"/><Field label="Outcome"/><Field label="Failure / Limitation" full area/><Field label="Additional Information" full area/><Field label="Source URL (optional)"/></div><div style={{display:'flex',justifyContent:'flex-end',marginTop:16}}><button className="btn primary" onClick={start} disabled={running}>{running?'Creating…':'Create Project'}<Sparkles size={14}/></button></div></>}
function Field({label,full,area}:{label:string,full?:boolean,area?:boolean}){return <div className={`form-field ${full?'full':''}`}><label>{label}</label>{area?<textarea placeholder="Enter grounded source-backed details…"/>:<input placeholder="Enter value…"/>}</div>}
function Public(){return <div className="space-y"><div className="form-field"><label>Search documented projects…</label><input placeholder="e.g. abandoned predictive maintenance project"/></div><div className="grid grid-2"><SourceResult title="Low-power machine vision pilot" type="Academic project" domain="Computer Vision"/><SourceResult title="Water stress monitoring study" type="Research" domain="AgriTech"/><SourceResult title="Sensor-based inspection prototype" type="Open source" domain="Industrial IoT"/><SourceResult title="Remote asset anomaly detection" type="Challenge" domain="Infrastructure"/></div></div>}
function SourceResult({title,type,domain}:{title:string,type:string,domain:string}){return <div className="quick-link"><div><strong>{title}</strong><div style={{color:'#6c7681',fontSize:10,marginTop:4}}>{type} · {domain}</div></div><button className="btn">Import</button></div>}
